### ISSUE TITLE
background image

### ISSUE THREAD

**Issue by HHZZUUJH** [bludit-themes/clean-blog#1]
In the file index.php the background image is loaded from the web: $backgroundImage = 'https://source.unsplash.com/1600x900/?nature';

How can I include here own pictures on my webspace instead of the url?

Do I need my own license for https://source.unsplash.com/1600x900/?nature'?

**Comment by dignajar** [comment]
By default is using Unsplash free image repository. If you upload an image and set as cover image the theme is going to ignore get the image from Unsplash.
If you want to change the default images is here https://github.com/bludit-themes/clean-blog/blob/master/init.php
