### ISSUE TITLE
How can i change the Background/Header Image?

### ISSUE THREAD

**Issue by grizzee** [bludit-themes/clean-blog#3]
I want to replace the stockimages with my own

**Comment by dignajar** [comment]
You can change here.
https://github.com/bludit-themes/clean-blog/blob/master/init.php#L9

**Comment by grizzee** [comment]
Thanks. Is it possible to link to a folder of images or only to a unique Image?

**Comment by dignajar** [comment]
You can get all images from a folder and do some kind of random, but you need to set only one image at the time.

What you can do is set a `cover image` for each page you create and the theme is going to use that image.
